# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 490, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 490, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 490, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.TimeA = QtWidgets.QTimeEdit(self.centralwidget)
        self.TimeA.setGeometry(QtCore.QRect(80, 70, 118, 22))
        self.TimeA.setObjectName("TimeA")
        self.Time1 = QtWidgets.QLabel(self.centralwidget)
        self.Time1.setGeometry(QtCore.QRect(20, 70, 47, 14))
        self.Time1.setObjectName("Time1")
        self.TimeB = QtWidgets.QTimeEdit(self.centralwidget)
        self.TimeB.setGeometry(QtCore.QRect(80, 100, 118, 22))
        self.TimeB.setObjectName("TimeB")
        self.Time1_2 = QtWidgets.QLabel(self.centralwidget)
        self.Time1_2.setGeometry(QtCore.QRect(20, 100, 47, 14))
        self.Time1_2.setObjectName("Time1_2")
        self.TimeC = QtWidgets.QTimeEdit(self.centralwidget)
        self.TimeC.setGeometry(QtCore.QRect(80, 130, 118, 22))
        self.TimeC.setObjectName("TimeC")
        self.Time1_3 = QtWidgets.QLabel(self.centralwidget)
        self.Time1_3.setGeometry(QtCore.QRect(20, 130, 47, 14))
        self.Time1_3.setObjectName("Time1_3")
        self.TimeD = QtWidgets.QTimeEdit(self.centralwidget)
        self.TimeD.setGeometry(QtCore.QRect(80, 160, 118, 22))
        self.TimeD.setObjectName("TimeD")
        self.Time1_4 = QtWidgets.QLabel(self.centralwidget)
        self.Time1_4.setGeometry(QtCore.QRect(20, 160, 47, 14))
        self.Time1_4.setObjectName("Time1_4")
        self.TimeE = QtWidgets.QTimeEdit(self.centralwidget)
        self.TimeE.setGeometry(QtCore.QRect(80, 190, 118, 22))
        self.TimeE.setObjectName("TimeE")
        self.Time1_5 = QtWidgets.QLabel(self.centralwidget)
        self.Time1_5.setGeometry(QtCore.QRect(20, 190, 47, 14))
        self.Time1_5.setObjectName("Time1_5")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(210, 70, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(340, 60, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setGeometry(QtCore.QRect(290, 490, 118, 23))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Home"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop"))
        self.pushButton_3.setText(_translate("MainWindow", "Start Routine"))
        self.Time1.setText(_translate("MainWindow", "Time 1"))
        self.Time1_2.setText(_translate("MainWindow", "Time 2"))
        self.Time1_3.setText(_translate("MainWindow", "Time 3"))
        self.Time1_4.setText(_translate("MainWindow", "Time 4"))
        self.Time1_5.setText(_translate("MainWindow", "Time 5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
